name: Context deployment

on: 
  push:
    branches:
      - yaml_workflows

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo desde el primer job"

  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo desde el segundo job ${{ git.ref }}"